heat_template_version: 2014-10-16
description: HOT template for multiple net with VM

parameters:
  key_name:
    type: string
    description: Key Name

  public_net:
    type: string
    description: public network id

  web_flavor:
    type: string
    description: Flavor Name

  web_image:
    type: string
    description: Image Name
  app_flavor:
    type: string
    description: Flavor Name

  app_image:
    type: string
    description: Image Name
  
  dmz_name:
    type: string
  dmz_cidr:
    type: string
  dmz_gateway_ip:
    type: string
  dmz_host_routes:
    type: json
  dmz_allocation_pools:
    type: json
  dmz_dns_nameservers:
    type: comma_delimited_list
  dmz_enable_dhcp:
    type: string
  dmz_ip_version:
    type: number

  app_name:
    type: string
  app_cidr:
    type: string
  app_gateway_ip:
    type: string
  app_host_routes:
    type: json
  app_allocation_pools:
    type: json
  app_dns_nameservers:
    type: comma_delimited_list
  app_enable_dhcp:
    type: string
  app_ip_version:
    type: number

  db_name:
    type: string
  db_cidr:
    type: string
  db_gateway_ip:
    type: string
  db_host_routes:
    type: json
  db_allocation_pools:
    type: json
  db_dns_nameservers:
    type: comma_delimited_list
  db_enable_dhcp:
    type: string
  db_ip_version:
    type: number

resources:

  router1:
    type: OS::Neutron::Router
    properties:
      external_gateway_info:
        network: { get_param: public_net }
     
  dmz_zone:
    type: Lib::Stack::Net
    properties:
      name: { get_param: dmz_name }
      cidr: { get_param: dmz_cidr }
      gateway_ip: { get_param: dmz_gateway_ip }
      host_routes: { get_param: dmz_host_routes }
      allocation_pools: { get_param: dmz_allocation_pools }
      enable_dhcp: { get_param: dmz_enable_dhcp }
      ip_version: { get_param: dmz_ip_version }
      dns_nameservers: { get_param: dmz_dns_nameservers }
      router_id: { get_resource: router1 }

  app_zone:
    type: Lib::Stack::Net
    properties:
      name: { get_param: app_name }
      cidr: { get_param: app_cidr }
      gateway_ip: { get_param: app_gateway_ip }
      host_routes: { get_param: app_host_routes }
      allocation_pools: { get_param: app_allocation_pools }
      enable_dhcp: { get_param: app_enable_dhcp }
      ip_version: { get_param: app_ip_version }
      dns_nameservers: { get_param: app_dns_nameservers }
      router_id: { get_resource: router1 }

  db_zone:
    type: Lib::Stack::Net
    properties:
      name: { get_param: db_name }
      cidr: { get_param: db_cidr }
      gateway_ip: { get_param: db_gateway_ip }
      host_routes: { get_param: db_host_routes }
      allocation_pools: { get_param: db_allocation_pools }
      enable_dhcp: { get_param: db_enable_dhcp }
      ip_version: { get_param: db_ip_version }
      dns_nameservers: { get_param: db_dns_nameservers }
      router_id: { get_resource: router1 }

  web1:
    type: Lib::Stack::WebFip
    depends_on: [ dmz_zone, install_web ]
    properties:
      key_name: { get_param: key_name }
      instance1_flavor: { get_param: web_flavor }
      instance1_image: { get_param: web_image }
#      instance1_vol_size: { get_param: web_vol_size }
#      instance1_vol_type: { get_param: web_vol_type }
      public_net_id: { get_param: public_net }
      private_net_id: { get_attr: [dmz_zone, net_id] }
      private_subnet_id: { get_attr: [dmz_zone, subnet_id] }
      user_data: { get_attr: [ install_web, userdata ] }

  install_web:
    type: Lib::Stack::UserDataDb
    properties:
      public_ip: ''
      app_ip: 'toto'
#      app_ip: { get_attr: [app1, first_address] }

  app1:
    type: Lib::Stack::Server
    depends_on: [ app_zone, install_app ]
    properties:
      key_name: { get_param: key_name }
      instance1_flavor: { get_param: app_flavor }
      instance1_image: { get_param: app_image }
#      instance1_vol_size: { get_param: app_vol_size }
#      instance1_vol_type: { get_param: web_vol_type }
#      public_net_id: { get_param: public_net }
      private_net_id: { get_attr: [app_zone, net_id] }
      private_subnet_id: { get_attr: [app_zone, subnet_id] }
      user_data: { get_attr: [ install_app, userdata ] }

  install_app:
    type: Lib::Stack::UserDataDb
    properties:
      public_ip: ''
      app_ip: 'toto'
#      app_ip: { get_attr: [app1, first_address] }


outputs:
  web1_public_ip:
    description: Floating IP address of web1
    value: { get_attr: [ web1, floating_ip_address ] }
  web1_private_ip:
    description: Private IP address of web1
    value: { get_attr: [ web1, first_address ] }
  app1_private_ip:
    description: Private IP address of app1
    value: { get_attr: [ app1, first_address ] }

