heat_template_version: 2014-10-16

# NOTE: You don't need to pass the parameter explicitly from the
# parent template, it can be specified via the parameter_defaults
# in the resource_registry instead, if you want to override the default
# and/or share values with other templates in the tree.
parameters:
  public_ip:
    type: string
  app_ip:
    type: string

resources:
  userdata:
    type: OS::Heat::MultipartMime
    properties:
      parts:
      - config: {get_resource: user_config}
      - config: {get_resource: install_ansible}
      - config: {get_resource: gen_ansible_mysql}
      - config: {get_resource: gen_ansible_playbook}
      - config: {get_resource: gen_ansible_hosts}
      - config: {get_resource: gen_ansible_vars}
      - config: {get_resource: gen_run_ansible}
#      - config: {get_resource: run_ansible}

  user_config:
    type: Lib::Stack::UserData::Init
#
#    type: OS::Heat::CloudConfig
#    properties:
#      cloud_config:
#        preserve_hostname: true
#        manage_etc_hosts: false
#        bootcmd:
#          - cloud-init-per instance my_set_hostname sh -xc "wget -O - -q http://169.254.169.254/latest/meta-data/local-hostname > /etc/hostname ; hostname -F /etc/hostname"
#          - cloud-init-per instance my_set_hosts sh -xc "sed -i -e '/^127.0.1.1/d' /etc/hosts;  ( echo -n '127.0.1.1 ' ; cat /etc/hostname; echo ) >> /etc/hosts"

  install_ansible:
    type: OS::Heat::CloudConfig
    properties:
      cloud_config:
        merge_how: 'list(append)+dict(recurse_array)+str()'
        write_files:
        - path: /root/install_ansible.sh
          content:
            str_replace:
              template:
                get_file: ../config-scripts/script-install-ansible.sh
              params:
                $public_ip: { get_param: public_ip }
          owner: root:root
          permissions: '0755'
        runcmd:
          - /root/install_ansible.sh

  gen_ansible_mysql:
    type: OS::Heat::CloudConfig
    properties:
      cloud_config:
        merge_how: 'list(append)+dict(recurse_array)+str()'
        write_files:
        - path: /root/install_ansible_mysql.sh
          content:
            str_replace:
              template:
                get_file: ../config-scripts/script-install-ansible-mysql.sh
              params:
                $public_ip: { get_param: public_ip }
          owner: root:root
          permissions: '0755'
        runcmd:
          - /root/install_ansible_mysql.sh

  gen_ansible_playbook:
    type: OS::Heat::CloudConfig
    properties:
      cloud_config:
        merge_how: 'list(append)+dict(recurse_array)+str()'
        write_files:
        - path: /root/ansible/local.yaml
          content:
            str_replace:
              template:
                get_file: ../ansible/local.yaml
              params:
                $public_ip: { get_param: public_ip }
          owner: root:root
          permissions: '0644'

  gen_ansible_vars:
    type: OS::Heat::CloudConfig
    properties:
      cloud_config:
        merge_how: 'list(append)+dict(recurse_array)+str()'
        write_files:
        - path: /root/ansible/group_vars/mysql.yaml
          content:
            str_replace:
              template:
                get_file: ../ansible/group_vars/mysql.yaml
              params:
                $public_ip: { get_param: public_ip }
          owner: root:root
          permissions: '0644'

  gen_ansible_hosts:
    type: OS::Heat::CloudConfig
    properties:
      cloud_config:
        merge_how: 'list(append)+dict(recurse_array)+str()'
        write_files:
        - path: /root/ansible/hosts
          content:
            str_replace:
              template:
                get_file: ../ansible/hosts
              params:
                $public_ip: { get_param: public_ip }
          owner: root:root
          permissions: '0644'

  gen_run_ansible:
    type: OS::Heat::CloudConfig
    properties:
      cloud_config:
        merge_how: 'list(append)+dict(recurse_array)+str()'
        write_files:
        - path: /root/run_ansible.sh
          content:
            str_replace:
              template:
                get_file: ../config-scripts/script-run-ansible.sh
              params:
                $public_ip: { get_param: public_ip }
          owner: root:root
          permissions: '0755'
        runcmd:
          - /root/run_ansible.sh


outputs:
  # This means get_resource from the parent template will get the userdata, see:
  # http://docs.openstack.org/developer/heat/template_guide/composition.html#making-your-template-resource-more-transparent
  # Note this is new-for-kilo, an alternative is returning a value then using
  # get_attr in the parent template instead.
  userdata:
    value: {get_resource: userdata}
