heat_template_version: 2014-10-16

# NOTE: You don't need to pass the parameter explicitly from the
# parent template, it can be specified via the parameter_defaults
# in the resource_registry instead, if you want to override the default
# and/or share values with other templates in the tree.
parameters:
  public_ip:
    type: string
  app_ip:
    type: string

resources:
  userdata:
    type: OS::Heat::MultipartMime
    properties:
      parts:
      - config: {get_attr: [user_config, userdata]}
      - config: {get_resource: launch_config}
#      - config: {get_resource: install_app}

  user_config:
    type: Lib::Stack::UserData::Init

  launch_config:
    type: OS::Heat::CloudConfig
    properties:
      cloud_config:
        write_files:
        - path: /root/launch.sh
          content:
            str_replace:
              template:
                get_file: ../config-scripts/script-install-apache.sh
              params:
                $public_ip: { get_param: public_ip }
          owner: root:root
          permissions: '0755'
        runcmd:
          - /root/launch.sh

outputs:
  # This means get_resource from the parent template will get the userdata, see:
  # http://docs.openstack.org/developer/heat/template_guide/composition.html#making-your-template-resource-more-transparent
  # Note this is new-for-kilo, an alternative is returning a value then using
  # get_attr in the parent template instead.
  userdata:
    value: {get_resource: userdata}
