heat_template_version: 2014-10-16

# NOTE: You don't need to pass the parameter explicitly from the
# parent template, it can be specified via the parameter_defaults
# in the resource_registry instead, if you want to override the default
# and/or share values with other templates in the tree.
parameters:
  master_jenkins:
    type: string

resources:
  userdata:
    type: OS::Heat::MultipartMime
    properties:
      parts:
      - config: {get_attr: [user_config,userdata]}
      - config: {get_resource: get_jenkins}
      - config: {get_resource: run_jenkins}

  user_config:
    type: Lib::Stack::UserData::Init

  get_jenkins:
    type: OS::Heat::SoftwareConfig
    properties:
      config:
        get_file: ./files/get_jenkins_slave.sh

  run_jenkins:
    type: OS::Heat::SoftwareConfig
    properties:
      config:
        str_replace:
          params:
            $master_jenkins: { get_param: master_jenkins }
          template:
            get_file: ./files/run_jenkins_slave.sh

outputs:
  # This means get_resource from the parent template will get the userdata, see:
  # http://docs.openstack.org/developer/heat/template_guide/composition.html#making-your-template-resource-more-transparent
  # Note this is new-for-kilo, an alternative is returning a value then using
  # get_attr in the parent template instead.
  userdata:
    value: {get_resource: userdata}
