heat_template_version: 2014-10-16

# NOTE: You don't need to pass the parameter explicitly from the
# parent template, it can be specified via the parameter_defaults
# in the resource_registry instead, if you want to override the default
# and/or share values with other templates in the tree.
parameters:
  private_net_id:
    type: string

resources:
  userdata:
    type: OS::Heat::MultipartMime
    properties:
      parts:
      - config: {get_attr: [user_config,userdata]}
      - config: {get_resource: install_ansible}

  user_config:
    type: Lib::Stack::UserData::Init

  install_ansible:
    type: OS::Heat::CloudConfig
    properties:
      cloud_config:
        merge_how: 'list(append)+dict(recurse_array)+str()'
        write_files:
        - path: /root/run_ansible.sh
          owner: root:root
          permissions: '0755'
          content:
            get_file: ./files/run_ansible.sh
        - path: /root/os_image_factory_install.sh
          owner: root:root
          permissions: '0755'
          content:
            get_file: ./files/os_image_factory_install.sh
        - path: /root/os_image_factory/setup/os_image_factory.playbook.yml
          owner: root:root
          permissions: '0644'
          content:
            get_file: ./files/os_image_factory.playbook.yml
        - path: /var/lib/jenkins/.profile
          permissions: '0644'
          owner: jenkins:jenkins
          content:
            str_replace:
              params:
                $network_id: { get_param: private_net_id }
              template:
                get_file: ./files/jenkins.profile
        runcmd:
          - /root/os_image_factory_install.sh
          - sleep 2
          - /root/run_ansible.sh

outputs:
  # This means get_resource from the parent template will get the userdata, see:
  # http://docs.openstack.org/developer/heat/template_guide/composition.html#making-your-template-resource-more-transparent
  # Note this is new-for-kilo, an alternative is returning a value then using
  # get_attr in the parent template instead.
  userdata:
    value: {get_resource: userdata}
