---
- hosts: mysqlserver
  gather_facts: no

  tasks:
  - name: ensure apt cache is up to date
    apt: update_cache=yes
  - name: ensure packages are installed
    apt: name={{item}}
    with_items:
        - mysql-common
        - mysql-server
        - python-mysqldb

- hosts: mysqlserver
  gather_facts: yes

  tasks:
  - name: ensure database is created
    mysql_db: name={{dbname}} state=present

  - name: ensure mysql is running
    service: name=mysql state=running enabled=yes

  - name: delete all user
    mysql_user: name={{dbuser}} state=absent

  - name: ensure user has access to database
    mysql_user: name={{dbuser}} password={{dbpassword}} priv={{dbname}}.*:ALL host='%'

